### ISSUE TITLE
CLI API Documentation

### ISSUE THREAD

**Issue by karthikmallireddy** [duckdb/duckdb-web#105]
Hi,

When can we expect the documentation notes for the bellow link??

https://duckdb.org/docs/api/cli

**Comment by karthikmallireddy** [comment]
Can Someone Please respond to this ticket

**Comment by hannesmuehleisen** [comment]
Hello, you seem to think that we somehow owe you documentation within a certain time frame or a response on your request in the first place. I'm afraid it's not how Open Source works. Let me briefly explain: we provide software and documentation as-is and expect nothing in return. But at the same time you don't get to decide what we are working on and when. 

If you want this addressed, the best way is to send us a pull request yourself. If you are unable to do so, you are of course invited to file an issue as you have. But let me tell you, the tone of your issue and subsequent comment can be much improved, because right now we perceive it as very rude. I will close this issue because of it.

**Comment by karthikmallireddy** [comment]
I'm not here to debate or argue I'm just asking a question, I don't think you can understand my tone with out listening if words hurt t

> Hello, you seem to think that we somehow owe you documentation within a certain time frame or a response on your request in the first place. I'm afraid it's not how Open Source works. Let me briefly explain: we provide software and documentation as-is and expect nothing in return. But at the same time you don't get to decide what we are working on and when.
> 
> If you want this addressed, the best way is to send us a pull request yourself. If you are unable to do so, you are of course invited to file an issue as you have. But let me tell you, the tone of your issue and subsequent comment can be much improved, because right now we perceive it as very rude. I will close this issue because of it.
> 
> See also: https://berthub.eu/articles/posts/anonymous-help/

First thing I'm not rude or questioning anyone in the eco system, Hope you can understand messages can't interpret my tone Since I like this tool very much and I'm just curious to ask when will the documentation will be available for the CLI that's all Hope you understand and wait till the documentation is publicly available and thanks for your all inputs.
