### ISSUE TITLE
Vacuum docs should be updated to remove no-op comment

### ISSUE THREAD

**Issue by Mause** [duckdb/duckdb-web#1331]
`VACUUM` now actually does something, see:

 * https://github.com/duckdb/duckdb/pull/7794
 * https://github.com/duckdb/duckdb/pull/7824
 * https://github.com/duckdb/duckdb/issues/109
 * https://github.com/duckdb/duckdb/issues/9263

**Comment by Mytherin** [comment]
It only vacuums indexes currently - not yet tables

**Comment by taniabogatsch** [comment]
The index vacuum functionality is not coupled to the `VACUUM` statement. It happens implicitly after each operation/query altering the index. For example, after inserting 1M new values, the index will trigger a vacuum operation if the potential freeable memory passes a threshold. This happens in the `LocalStorage::Flush`, without the need to call `VACUUM` explicitly. I've also added similar code to clean up the index at locations other than `LocalStorage::Flush`, e.g., when rolling back due to a constraint violation, deleting from an index, etc.

```cpp
	// possibly vacuum any excess index data
	table.info->indexes.Scan([&](Index &index) {
		index.Vacuum();
		return false;
	});
```

As far as I can remember I have not touched `VACUUM` 🤔.

**Comment by taniabogatsch** [comment]
@szarnyasg: other than postgres, we never rebuild indexes. This [PR](https://github.com/duckdb/duckdb/pull/9339) removes the last code paths that do so when replaying the WAL. Once this is merged, we only build indexes when creating them and then only alter them in any subsequent queries.

**Comment by szarnyasg** [comment]
Thanks. So the plain `VACUUM` is still doing a no-op. I'm pushing some minor adjustments to the docs and closing this.
