### ISSUE TITLE
Document `CREATE TEMP TABLE...`

### ISSUE THREAD

**Issue by ajzo90** [duckdb/duckdb-web#181]
I can not find any description on what a `TEMP` or `TEMPORARY` table is in `CREATE TEMP TABLE...` statements. Would be helpful with a brief description on this page https://duckdb.org/docs/sql/statements/create_table

One use case I have is that I consider it for "caching" aggregates:
`create tmp as select user, count(*) v ...` and then run queries like this `select city, sum(v) v ... from tmp`. 

Is it materialised in memory? What if it does not fit in memory?
Is it removed automatically? When? How? 
What is the intended use case for temporary tables?

**Comment by Mytherin** [comment]
> The tables reside in memory, but I am not certain what happens if they exceed memory (@Mytherin or @hannes happen to know?) . I believe that they would use a temporary file if they exceeded memory?

If a temp_directory is specified chunks of the temporary table can indeed be off-loaded to disk as required. If not then an error will be thrown.

**Comment by hawkfish** [comment]
There are basically two styles of "temporary tables" out there: global and session scoped. 

Global tables are permanent tables that have a globally defined schema, but the data is private to the session (e.g., [Oracle](https://www.oracletutorial.com/oracle-basics/oracle-global-temporary-table/). One nasty problem with them is that you can't use them for the kind of local analytics you are describing because the temporary table name is global. This is problematic for query generating systems (like Tableau, which is where I ran into this).

Fortunately, as a single user system, DuckDB supports session scoped temporary tables. Using them to cache expensive intermediate results such as rollups is a common use case, so go for it!
