### ISSUE TITLE
Installation page refinements

### ISSUE THREAD

**Issue by szarnyasg** [duckdb/duckdb-web#2372]
* [ ] The sections stating `Currently not available` should be removed. This will reveals some bugs in the selection mechanism, these should be fixed.
* [ ] The page should detect the CPU type. This applies both to the landing page (e.g. for the Linux CLI client) and to the detailed installation page.
* [ ] Add Wasm to the detailed installation page.
* [ ] The installation page currently has a query string but if the link is opened, the query string has no effect: the site jumps back to the default auto-detected view (e.g. macOS + CLI + stable).

**Comment by ned2** [comment]
hey @szarnyasg something else perhaps to consider: when the _Package manager_ option is selected for both Windows and macOS the provided _Usage example_ still indicates the path `./duckdb` rather than the bare executable `duckdb` which respective package manager should have added to the user's PATH. (have tested that works as expected with brew on macOS but not winget on Windows)

**Comment by szarnyasg** [comment]
Good point, thanks! We'll work this into the installation page.

**Comment by szarnyasg** [comment]
I wrote these up in a document and passed it along the design team.
